### ISSUE TITLE
Fix documentation issues

### ISSUE THREAD

**Issue by lewismc** [lewismc/podaacpy#14]
http://podaacpy.readthedocs.io/en/latest/webservices.html

This is not correct and needs to be resolved.
Building and testing the documentation locally is also documented at https://github.com/lewismc/podaacpy#documentation

**Comment by lewismc** [comment]
@Omkar20895

**Comment by Omkar20895** [comment]
@lewismc I am feeling sleepy and I think I am messing this all up in my dizziness. Please pardon me. Can I look into it with a fresh mind when I wake up?? Thanks

**Comment by lewismc** [comment]
No problems @Omkar20895 rhanks

**Comment by Omkar20895** [comment]
@lewismc I have built the docs locally and they were working absolutely fine.

**Comment by Omkar20895** [comment]
There is a '\' missing in the podaac.py file line 86. This is a syntax error and I think the build might be failing bacause of this. I am sending a pull request and will be merging it and I hope that will work.

**Comment by lewismc** [comment]
ok thanks

**Comment by lewismc** [comment]
This is resolved now :)

**Comment by Omkar20895** [comment]
Pheww! Finally! 😄  Thanks @lewismc

**Comment by Omkar20895** [comment]
@lewismc are you sure that this issue is fixed? Because when I open this link it seems that there is an issue still. Thanks :)

**Comment by lewismc** [comment]
You are right @Omkar20895 it is still broken. God almighty.

**Comment by Omkar20895** [comment]
@lewismc what do we do about this?? I am unable to find any reason for its failure and its annoying me. Please let me know your thoughts.

**Comment by lewismc** [comment]
All that is left currently broken is the utilities documentatio. Good work @Omkar20895

**Comment by Omkar20895** [comment]
@lewismc All the issues with the documentation have been resolved, everything is working OK, I am resolving the issue. Thanks.

**Comment by lewismc** [comment]
Excellent good work.
