### ISSUE TITLE
PODAAC Solr search server down

### ISSUE THREAD

**Issue by Omkar20895** [lewismc/podaacpy#25]
- The server @ http://podaac.jpl.nasa.gov/dmasSolr/solr/ is not up yet.
- I have posted a thread in the forum @ https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=6&t=367
- We need to await the reply in the thread and if there is none then I think we need to find an alternative.

**Comment by lewismc** [comment]
Thanks Omkar nice

On Wednesday, June 15, 2016, Omkar <notifications@github.com> wrote:

>
>    - The server @ http://podaac.jpl.nasa.gov/dmasSolr/solr/ is not up yet.
>    - I have posted a thread in the forum @
>    https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=6&t=367
>    - We need to await the reply in the thread and if there is none then I
>    think we need to find an alternative.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lewismc/podaacpy/issues/25>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABHJlz9UXGax8hxQfof7RdBxsnU13Xopks5qL7zpgaJpZM4I2IZu>
> .
>


-- 
*Lewis*

**Comment by lewismc** [comment]
So as it turns out the server is not down at all... you are just using the wrong server!

The following lines need to be changed ASAP

https://github.com/lewismc/podaacpy/blob/master/podaac/podaac.py#L455
https://github.com/lewismc/podaacpy/blob/master/podaac/podaac.py#L485

Please update this PR ASAP thanks @Omkar20895

**Comment by Omkar20895** [comment]
Yeah sure.

**Comment by Omkar20895** [comment]
@lewismc This issue has been solved and I am closed it. Thanks.

**Comment by lewismc** [comment]
Thanks

On Thursday, June 16, 2016, Omkar <notifications@github.com> wrote:

> Closed #25 <https://github.com/lewismc/podaacpy/issues/25>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lewismc/podaacpy/issues/25#event-694564744>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABHJl3R5PL4N9iZc1nxdmac-sDXqCjBbks5qMUOAgaJpZM4I2IZu>
> .
>


-- 
*Lewis*
