### ISSUE TITLE
Add requires.io support

### ISSUE THREAD

**Issue by lewismc** [lewismc/podaacpy#30]
https://requires.io/

**Comment by lewismc** [comment]
@Omkar20895 please update setup.py as per http://python-packaging.readthedocs.io/en/latest/dependencies.html to include all of the dependencies

**Comment by Omkar20895** [comment]
@lewismc Done. Thanks.

**Comment by lewismc** [comment]
Nice

**Comment by Omkar20895** [comment]
![screen shot 2016-07-09 at 10 55 04 am](https://cloud.githubusercontent.com/assets/11131863/16706280/af6221b8-45c3-11e6-8c39-7764e0f686d2.png)

@lewismc Requirements up to date and setup.py covers all the requirements too, we can close this issue now.
