### ISSUE TITLE
Add PyPi version and downloads badge

### ISSUE THREAD

**Issue by Omkar20895** [lewismc/podaacpy#33]
- We also need to add a PyPi version badge which looks like this
![screen shot 2016-06-30 at 12 27 33 pm](https://cloud.githubusercontent.com/assets/11131863/16479494/461bc13e-3ebe-11e6-98a6-4dbb5efd32d8.png)

**Comment by lewismc** [comment]
Please progress with this @Omkar20895

**Comment by Omkar20895** [comment]
@lewismc we need to host it on pip before we could add this badge. Thanks. :)

**Comment by Omkar20895** [comment]
@lewismc we need to host the package in PyPi so that it can be imported in ocw, the build would fail until then, even though the data source is added to ocw. Thanks.

**Comment by lewismc** [comment]
Ok ill push today
