### ISSUE TITLE
Subset and download l3 and l4 subsetted datasets 

### ISSUE THREAD

**Issue by Omkar20895** [lewismc/podaacpy#35]
- I have been investigating how to subset and download l3 and l4 datasets, since I am new to this I have been facing some confusions.
- I am discussing over this[0] thread in the podaac forum.
- This should be hopefully solved soon.

[0] https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=5&t=219

**Comment by lewismc** [comment]
@Omkar20895 please paste the XML here and format it. It is a large XML file and I don't knwow hich snippet you are referring to. Thanks

**Comment by lewismc** [comment]
If the data contains XML metadata child elements which are <Grid> then you would be wise to assume that the data is gridded ;)

**Comment by lewismc** [comment]
Is this addressed @Omkar20895 ? Did you have a PR for the subsetting within l4 granule function?

**Comment by Omkar20895** [comment]
No not yet, I have been caught up in the long weekend we had here, I will get onto this now, sorry for the delay, thanks. :)

**Comment by lewismc** [comment]
Closing this as it is not relevant for 1.1.0 now given the new L2SS API
