### ISSUE TITLE
load_image_granule() does not exist

### ISSUE THREAD

**Issue by Omkar20895** [lewismc/podaacpy#39]
- The Image Granule web service is not returning any content upon querying. 
- I have opened a thread here [0] and hopefully it should resolve soon. 
- The podaac service is quite unstable and it turning out to be PITA  for us :P 

[0] https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=6&t=384

**Comment by Omkar20895** [comment]
@lewismc the return statement in the load_image_granule() returns a HTTP message headers  
![screen shot 2016-07-15 at 3 12 25 am](https://cloud.githubusercontent.com/assets/11131863/16856848/067d49b2-4a3a-11e6-9e4f-8570798cab12.png)

The output of this function is 
![screen shot 2016-07-15 at 3 13 29 am](https://cloud.githubusercontent.com/assets/11131863/16856867/238ab36e-4a3a-11e6-907c-85a176941892.png)

the function also downloads an image in the same directory.

**Comment by lewismc** [comment]
ACK

**Comment by Omkar20895** [comment]
The same exact thing happens with the extract_granule() function. :)

**Comment by Omkar20895** [comment]
This issue has been resolved by the podaac forum. Thanks. :)
