### ISSUE TITLE
Discrepancies in the documentation.

### ISSUE THREAD

**Issue by Omkar20895** [lewismc/podaacpy#4]
There are some discrepancies in the Retrieve granule images, the field in the arguments to the function is given as 'styles' rather than 'style' and also there is a new unknown parameter 'transparency=true' which is used, this parameter causes the function to fail with an error

**Comment by Omkar20895** [comment]
I can't get it, in the documentation of podaac image granule the set of acceptable parameters does not include the 'transparent' parameter. 

But, the url http://podaac.jpl.nasa.gov/ws/image/granule?shortName=ASCATB-L2-25km&granuleName=ascat_20121114_035403_metopb_00817_eps_o_250_2101_ovw.l2.nc&request=GetMap&layers=wind_speed&styles=&version=1.3.0&format=image/png&srs=&bbox=-180,-66.43,180,79.91&height=300&width=600&service=WMS&transparent=True as you can see has a parameter transparent set in the end to be true and return an image. Please look into it and help me out.

**Comment by lewismc** [comment]
Will do

On Saturday, April 16, 2016, Omkar <notifications@github.com> wrote:

> I can't get it, in the documentation of podaac image granule the set of
> acceptable parameters does not include the 'transparent' parameter.
>
> But, the url
> http://podaac.jpl.nasa.gov/ws/image/granule?shortName=ASCATB-L2-25km&granuleName=ascat_20121114_035403_metopb_00817_eps_o_250_2101_ovw.l2.nc&request=GetMap&layers=wind_speed&styles=&version=1.3.0&format=image/png&srs=&bbox=-180,-66.43,180,79.91&height=300&width=600&service=WMS&transparent=True
> as you can see has a parameter transparent set in the end to be true and
> return an image. Please look into it and help me out.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewismc/podaacpy/issues/4#issuecomment-210848809>
>


-- 
*Lewis*

**Comment by lewismc** [comment]
Is this done @Omkar20895 ?

**Comment by Omkar20895** [comment]
Yes this was just a false alarm. The transparent parameter does not make much difference. We get the same image either ways(call using 'transparent' parameter or without it). Thanks.

**Comment by Omkar20895** [comment]
I have changed the documentation and referred it above. Please look into it and ping me a GO for closing this if everything looks good.

**Comment by lewismc** [comment]
Thanks @Omkar20895  you are also now a mentor if this codebase so feel free to merge but also realise that there are others who will use your code and also review you based upon you code.
For ample, eventually I see this code being here
https://github.com/nasa
Why?
Because it has better vision. That is all. 
The code you and I write now will be used by many. Please be mindful of this when you write your code.

**Comment by Omkar20895** [comment]
Thanks @lewismc. I will keep that in mind. :)

**Comment by lewismc** [comment]
Thanks
