### ISSUE TITLE
Add dependencies to setup.py

### ISSUE THREAD

**Issue by lewismc** [lewismc/podaacpy#46]
We need to add the dependencies to [setup.py](https://github.com/lewismc/podaacpy/blob/master/setup.py#L40).

**Comment by lewismc** [comment]
This issue relates to https://github.com/rtfd/readthedocs-sphinx-ext/issues/23

**Comment by lewismc** [comment]
Now MCC is working
http://podaacpy.readthedocs.io/en/latest/mcc.html

**Comment by lewismc** [comment]
Utilities and services is still broken

**Comment by Omkar20895** [comment]
beautifulsoup is already in the dependencies. 
I think there are redundant dependencies in utilities and data_source. I am removing them right away. Thanks.
