### ISSUE TITLE
Fix landscape.io issues

### ISSUE THREAD

**Issue by lewismc** [lewismc/podaacpy#48]
Hi @Omkar20895 can you please have a look at
https://landscape.io/github/lewismc/podaacpy/26/messages/style
Thanks

**Comment by Omkar20895** [comment]
OMG! there are 47 warnings and that too most of them related to arguments being uppercase!

**Comment by lewismc** [comment]
Yes, quite a few. Can you take a look?

**Comment by Omkar20895** [comment]
@lewismc I have taken a clear look at all the warnings, most of them say that arguments/functionName should be lowercase, they are practices that you need to follow, I think this is trivial but should not be neglected.

**Comment by lewismc** [comment]
Can you fix it them...?

**Comment by lewismc** [comment]
If you don't then I will.
What is going on with https://github.com/apache/climate/pull/383 ?
It is still broken and GSoC is coming to an end.
What is going on here @Omkar20895  ?

**Comment by Omkar20895** [comment]
yes I will fix them.
