### ISSUE TITLE
Error in installing podaacpy

### ISSUE THREAD

**Issue by Omkar20895** [lewismc/podaacpy#53]
- When I tried to install podaacpy from the cheeseshop I am getting this error. 
![screen shot 2016-08-20 at 2 10 48 pm](https://cloud.githubusercontent.com/assets/11131863/17830137/5f2f5b82-66e0-11e6-9628-26fecff7369b.png)

- I cross checked this with Ibrahim, he too got the same error.

**Comment by Omkar20895** [comment]
This might be because the pip package contains README.rst but not README.md

**Comment by jarifibrahim** [comment]
Add `pypandoc` to requirements. This should fix it.

**Comment by Omkar20895** [comment]
Yes that fixed it for me. Thanks @jarifibrahim.

**Comment by jarifibrahim** [comment]
@Omkar20895 Only adding `pypandoc` to dependencies won't work. Pypandoc requires pandoc which needs to be installed as well. 

Please take a look at the installation instructions here https://pypi.python.org/pypi/pypandoc/

**Comment by Omkar20895** [comment]
@lewismc we can do one thing instead of adding this dependency, we can have two readme files like 'readme.md' and also readme.rst.

**Comment by jarifibrahim** [comment]
@Omkar20895 See the following code from `setup.py`
```
try:
    import pypandoc
    _long_description = pypandoc.convert(
        source='README.md',
        format='markdown_github',
        to='rst',
        outputfile='README.rst')
except(IOError, ImportError):
    _long_description = open('README.md').read()

open('doc.txt', 'w').write(_long_description)
```
The `pypandoc` is used to convert the `README.md` file (if it exists) to `README.rst`  file. The `README.rst` file is then written to `doc.txt`. There's no point in having both `README.md` and `README.rst` file.

@lewismc Why is the doc created every time someone installs `podaac`? Can't we just put the docs along with the source code on pypi? I guess we could put a README file (generated from README.md file) directly on pypi.

**Comment by lewismc** [comment]
The 'doc.txt' is written to validate what the package landing page will look like at https://pypi.python.org/pypi/podaacpy

> here's no point in having both README.md and README.rst file.

Agreed, we can just use the README.rst which I just committed to master branch.
@Omkar20895 pleasse remove README.md and adapt setup.py accordingly. Thanks for pointing this out folks. By having README.rst we no longer require either pypandoc or pandoc.

**Comment by Omkar20895** [comment]
@lewismc done! Thanks.
