### ISSUE TITLE
Automated PyPI deployments using Travis CI

### ISSUE THREAD

**Issue by jarifibrahim** [lewismc/podaacpy#55]
Update `.travis.yml` to automatically deploy new releases to PyPI.

**Comment by Omkar20895** [comment]
@jarifibrahim do we have anything more to add to this??

**Comment by jarifibrahim** [comment]
We need two deploys 
1. For release to `pypitest` which will happen on every commit to master.
2. For release to `pypi` which will happen only on tagged commits (new releases).

**Comment by Omkar20895** [comment]
@jarifibrahim shall I assist you on this? I can also learn about how to do it along the way.

**Comment by jarifibrahim** [comment]
@Omkar20895 Sure. Take a look at this https://docs.travis-ci.com/user/deployment/pypi

**Comment by Omkar20895** [comment]
@jarifibrahim @lewismc everything looked good in .travis.yml file but the git log for the latest commit only showed the pypi deployment which was skipped since the commit was not tagged, but the "pypi test" deployment log was nowhere to be seen in the logs. Should we be concerned regarding this??
