### ISSUE TITLE
Add PyPI username and password in Travis.yml

### ISSUE THREAD

**Issue by jarifibrahim** [lewismc/podaacpy#57]
@lewismc Please add your username and password (encrypted) to `.travis.yml` file.

You'll need travis cli installed (instructions [here](https://github.com/travis-ci/travis.rb#installation))
Encrypted password can be generated using `travis encrypt 'plain-text-password'`

**Comment by lewismc** [comment]
@jarifibrahim username and password for Pypi?

**Comment by Omkar20895** [comment]
@lewismc yes, please take a look at [this](https://www.google.com/url?q=https%3A%2F%2Fwww.appneta.com%2Fblog%2Fpypi-deployment-with-travis-ci%2F&sa=D&sntz=1&usg=AFQjCNGit-N8ziV8bBLz_ax1PMn7vooSvg) for reference.

**Comment by lewismc** [comment]
Done, please see .travis.yml
