### ISSUE TITLE
Update Travis CI Build

### ISSUE THREAD

**Issue by jarifibrahim** [lewismc/podaacpy#62]
1. Make nosetests more verbal by adding `-v` flag
2. Fix `testpypi` deployment steps.
3. Cache pip dependencies
4. Disable email notification

**Comment by Omkar20895** [comment]
@jarifibrahim thanks for opening this issue, I was going to ping you on gchat for this. :)

**Comment by jarifibrahim** [comment]
@Omkar20895 No problem :)
