### ISSUE TITLE
Upgrade Podaacpy to PO.DAAC Web Services v3.2.2

### ISSUE THREAD

**Issue by lewismc** [lewismc/podaacpy#64]
August 25, 2016
We are pleased to announce the new version (v3.2.2) of the PO.DAAC Web Services now available online at http://podaac.jpl.nasa.gov/ws
 
PO.DAAC Web Services have been modified to conform to an updated API in the new HiTIDE/L2SS.  Also, there are significant changes in the Granule Subset web service.  The Granule Subset web service is now asynchronous, which prevents web timeouts and allows the subsetting of multiple granules in a single request.  A Granule Subset request is submitted, using http POST rather than GET, and a token is returned that can be used in the new Subset Status web service to determine the state of the Granule Subset request.  There is also a new Dataset Variables web service.

For questions or to provide feedback, please visit the PO.DAAC Web Services Forum

**Comment by Omkar20895** [comment]
@lewismc WTH! I did not see this coming, I will add new functions and tests to the podaac class. Thanks.

**Comment by Omkar20895** [comment]
@lewismc some of the previous web services have been completely removed!! ^_^

**Comment by lewismc** [comment]
@Omkar20895 yeah no joke. This is what we call [Sods Law](https://en.wikipedia.org/wiki/Sod's_law) HAHAHAHAHA

**Comment by lewismc** [comment]
Please update and merge and we can take it from there.

**Comment by Omkar20895** [comment]
@lewismc LOL! I think we need to have a gchat on this one probably this week to straighten the things out. Thanks.

**Comment by lewismc** [comment]
ack

**Comment by lewismc** [comment]
Hi @Omkar20895 when creating the new functions, can you please ensure that they mirror exactly that of the Web Services API e.g. the functions should be named

dataset_metadata 	
dataset_search 	
dataset_variables 	
granule_metadata 	
granule_preview 	
granule_subset 	
subset_status

we can then copy over the documentation from the PO.DAAC website so update all functions.

**Comment by Omkar20895** [comment]
@lewismc okay sure, do you want me to change the name of some old ones too? for example 'load_granule_md' to just 'dataset_metadata'? Thanks.

**Comment by lewismc** [comment]
Yes please. Lets make the Python API exactly as the Webservice specification.

**Comment by lewismc** [comment]
Good work @Omkar20895 this is grand.
