### ISSUE TITLE
Unable to find [URL Template] for accessing preview image

### ISSUE THREAD

**Issue by Omkar20895** [lewismc/podaacpy#69]
- I have opened an issue [here](https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=53&t=411), please refer to this for further information.

**Comment by Omkar20895** [comment]
@lewismc

**Comment by lewismc** [comment]
Workaround has been implemented and we can work towards improving within the 1.1.X development. Thanks @Omkar20895
