### ISSUE TITLE
webservices.html is not working again.

### ISSUE THREAD

**Issue by Omkar20895** [lewismc/podaacpy#73]
- Please refer to this [link](http://podaacpy.readthedocs.io/en/latest/webservices.html).
- When I build the documentation locally it works just fine and webservices.html works with the expected content in it.

@lewismc

**Comment by lewismc** [comment]
Yeah there is another issues somewhere which we need to resolve. This is a PITA. I am going to go ahead and push the release of Podaacpy 1.1.0 regardless. We can update the documentation at a later stage.

**Comment by Omkar20895** [comment]
Yes sure! @lewismc Thanks.

**Comment by lewismc** [comment]
All is good now http://podaacpy.readthedocs.io/en/latest/webservices.html

**Comment by Omkar20895** [comment]
awesome!

**Comment by Omkar20895** [comment]
@lewismc how did this issue resolve? I mean there was no code pushed regarding this that I could find, I am puzzled. Just curious.Thanks very much.

**Comment by lewismc** [comment]
It always seems to be the PEP8 which gets us. I formatted the code as follows and it wored fine.
```
autopep8 ./poddacpy --recursive --in-place --pep8-passes 2000 --verbose
```
