### ISSUE TITLE
Downloading subsetted dataset from PO.DAAC

### ISSUE THREAD

**Issue by Omkar20895** [lewismc/podaacpy#82]
- This issue is raised to track the issue raised in the PO.DAAC forum [here](https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=53&t=424).

**Comment by lewismc** [comment]
I just checked with one of the PO.DAAC engineers who manages to WebServices. Apparently the JSON response object from which we pull ```status``` also contains a list of ```download``` entries which contain URL links to the subsetted product.
We need to revisit this and also design a test for such. I'll debug and inspect the response myself later on.

**Comment by Omkar20895** [comment]
@lewismc I will write a unit test and I will let you know if there is anything of that sort. I was stuck in my academics these days. :)

**Comment by lewismc** [comment]
No problem, I am also going to have a look later tonight.

**Comment by Omkar20895** [comment]
I have checked the JSON response and yes it has a download URL once the subset job is done. I will send a PR with a new function that checks continuously for the given token and downloads the dataset once subset is done. Thanks.
