### ISSUE TITLE
Add recipe to conda-forge

### ISSUE THREAD

**Issue by agoodm** [lewismc/podaacpy#83]
Hi @lewismc and @Omkar20895 

In order to complete our mission to have OCW on conda forge, we need to ensure that all of its dependencies are also available on conda-forge. As of today, I believe `podaacpy` is the only one that is outstanding. Let me know if you would like me to push a `podaacpy` recipe to conda-forge, and if so whether or not you wish to be listed as maintainers. Additionally, the following changes need to be made in preparation for this undertaking:

- In setup.py, remove `coveralls` and any other dependencies not needed for runtime. This should be done to reduce bloat and to make it easier to build the package from the recipe in case some dependencies are missing from the main anaconda or conda-forge channels.
- `zip_safe` should be set to False. 
- Add a `MANIFEST.in` which includes the `LICENSE` file.

The latter two are needed since the maintainers of conda-forge want to make sure all packages on their channel include copies of the `LICENSE` file with each distribution in order to comply with the terms of the license. I can submit the PR for all of these if need be. Once done it would be ideal to also upgrade the package on PyPI to ensure the source distribution downloaded by conda contains the `LICENSE` file.

**Comment by lewismc** [comment]
Hi @agoodm I am on it right now.

> Let me know if you would like me to push a podaacpy recipe to conda-forge, and if so whether or not you wish to be listed as maintainers.

Yes please if you could push one then it would be greatly appreciated.
If we could also document this as the [Podaacpy wiki](https://github.com/lewismc/podaacpy/wiki) then it would also be appreciated such that one of us can replicate it in the future.

**Comment by agoodm** [comment]
Thanks @lewismc. If you can, you should probably update the package on PyPI too if you have not already to make sure the `LICENSE` file is included.

**Comment by lewismc** [comment]
Done @agoodm https://pypi.python.org/pypi/podaacpy/1.4.0

**Comment by agoodm** [comment]
@lewismc Can you add this to the wiki? I don't have commit writes so I can't edit it myself. You can place this section after "Publish to Pypi":

### Upload package to conda-forge

To update the package on conda-forge, fork our [feedstock repo](https://github.com/conda-forge/podaacpy-feedstock) and bump the version number in `recipe/meta.yaml` (it should be in the 2nd line of the file). If you are not already, you should also add your github username to the `recipe-maintainers` section. Commit your changes and submit a pull request, then merge if the CI tests are all green. conda-forge's CI services will then automatically rebuild the package from the newly updated recipe and upload the fully built package to their channel.

**Comment by lewismc** [comment]
beautiful... thank you @agoodm
