### ISSUE TITLE
future dependency missing in podaacpy conda recipe

### ISSUE THREAD

**Issue by agoodm** [lewismc/podaacpy#85]
Smoke tests are failing in  `ocw` Travis CI builds with `podaacpy` because the dependency `future` is missing from the recipe. This will also be a good opportunity to test the process of updating recipe files in conda-forge.

**Comment by lewismc** [comment]
OK, I'll go ahead and submit a PR in a branch on conda-forge then.

**Comment by agoodm** [comment]
The PR has already been made :stuck_out_tongue_closed_eyes:

**Comment by lewismc** [comment]
and boom goes the dynamite !!
