### ISSUE TITLE
Release 1.6.0 or patch 1.5.0?

### ISSUE THREAD

**Issue by agoodm** [lewismc/podaacpy#90]
Hi all,

Since #87 was resolved, I think it might be worthwhile for us to either create a new release, or manually apply the patch from #89 into our conda-forge recipe. What do you guys think?

**Comment by lewismc** [comment]
Release 1.6.0 BOOM. I'll spin it later today mate thanks @agoodm

**Comment by Omkar20895** [comment]
+1

**Comment by lewismc** [comment]
DONE
